FROM apache/airflow:2.9.2-python3.11

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        default-jre-headless \
        curl && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="$JAVA_HOME/bin:$PATH"

USER airflow

COPY airflow/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
